name: weight_watcher_ai
description: An AI-powered fitness app for tracking workouts, nutrition, and muscle gains with personalized insights.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Auth
  firebase_auth: ^4.20.0
  # Firebase Firestore
  cloud_firestore: ^4.17.5

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0

  # State Management
  provider: ^6.1.1

  # Data Persistence
  shared_preferences: ^2.2.2

  # Utilities
  uuid: ^4.2.2
  intl: ^0.19.0
  http: ^1.1.2

  # OpenAI Integration
  dart_openai: ^5.0.0
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.32.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Build & Deployment
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

# Flutter Configuration
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/data/ # Added data directory

  # The following section is for flutter_launcher_icons configuration
# Run this command to generate app icons:
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

# The following section is for flutter_native_splash configuration
# Run this command to generate splash screen:
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#6750A4"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#6750A4"
  web: false
