// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCo-HcNqxiHU-FIR7jW535Vy8Oww2EvOE',
    appId: '1:537518736466:web:9cbc34c000c68f38fc4b8b',
    messagingSenderId: '537518736466',
    projectId: 'weightwatcherai',
    authDomain: 'weightwatcherai.firebaseapp.com',
    storageBucket: 'weightwatcherai.firebasestorage.app',
    measurementId: 'G-KHYNP28GRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACUaM9X434a-nMVkfBZtUTcMvSC4pI6X0',
    appId: '1:537518736466:android:ca7ff6cce4894052fc4b8b',
    messagingSenderId: '537518736466',
    projectId: 'weightwatcherai',
    storageBucket: 'weightwatcherai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdIntT9Q84Ko1zNbHlk49qOB3ZIeRlswQ',
    appId: '1:537518736466:ios:7808fad4954a4893fc4b8b',
    messagingSenderId: '537518736466',
    projectId: 'weightwatcherai',
    storageBucket: 'weightwatcherai.firebasestorage.app',
    iosBundleId: 'com.example.weightWatcherAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdIntT9Q84Ko1zNbHlk49qOB3ZIeRlswQ',
    appId: '1:537518736466:ios:7808fad4954a4893fc4b8b',
    messagingSenderId: '537518736466',
    projectId: 'weightwatcherai',
    storageBucket: 'weightwatcherai.firebasestorage.app',
    iosBundleId: 'com.example.weightWatcherAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCo-HcNqxiHU-FIR7jW535Vy8Oww2EvOE',
    appId: '1:537518736466:web:5f0f1c5158cfe469fc4b8b',
    messagingSenderId: '537518736466',
    projectId: 'weightwatcherai',
    authDomain: 'weightwatcherai.firebaseapp.com',
    storageBucket: 'weightwatcherai.firebasestorage.app',
    measurementId: 'G-0WF18NYGY5',
  );

}